### ISSUE TITLE
Team related code is missing from auth

### ISSUE THREAD

**Issue by jorgt** [mynameisvasco/sveltekit-boilerplate#2]
`roles.ts` has only one entry called `Roles`, while drizzle is also requesting `TeamRoles`. I assume it's something like

```
export enum TeamRole {
	Member = 'team-member',
	Admin = 'team-admin'
}
```

I also can't find the methods for `findTeamById` and `findTeamMemberByUserId` in the auth repository used in `hooks.server.ts`

**Comment by mynameisvasco** [comment]
Fixed 49fdd221a623fedde7f5a223a3a5b064a3b31bf6
